name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: mergestat-linux-amd64
          - os: macos-latest
            asset_name: mergestat-macos-amd64

    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17.5
      id: go

    - name: Check out source
      uses: actions/checkout@v1

    - name: vet
      run: go vet -v ./...

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
    
    - name: test
      run: go test -v ./... -cover -covermode=count -coverprofile=coverage.out
    
    - name: upload coverage
      uses: codecov/codecov-action@v1
